wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1636495180
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.9.5
      5: 0.12.1
      8:
      - 3
      - 5
data:
  desc: null
  value:
    n_jobs: -1
    name: bike
